# Site settings
title: Brandon E. Salinas Sanchez
author:
  name: Brandon Salinas Sanchez
  email: bsalinassanchez@ucsd.edu
description: "Brandon's Portfolio Page"

minima:
  social_links:
    github: bsalinassanchez
    linkedin: bsalinassanchez

# Build settings
remote_theme: jekyll/minima
