# Site settings
title: Great New Blog Title
author:
  name: Brandon Salinas Sanchez
  email: bsalinassanchez@ucsd.edu
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
